import csv

with open('test.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        myfile = open('new.xml', 'a')
        mystring = ''
        if line_count == 0:
            mystring += """<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<!DOCTYPE data [
	<!ELEMENT data (sql+)>
	<!ELEMENT sql EMPTY>
	<!ATTLIST sql
	query CDATA #IMPLIED
		update CDATA #IMPLIED
>
]>\n"""
            mystring += '<data>\n'
        mystring += '\tupdate ' + row[0] + ' from ' + row[1] + "\n"
        myfile.writelines(mystring)
        line_count += 1

    myfile.writelines('</data>')
    myfile.close()

